// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeZKHgTw0oH_rJKPoA0pR3OvYV7f0b-lI',
    appId: '1:701912503570:web:c937e0cbf637acf4ba8fcb',
    messagingSenderId: '701912503570',
    projectId: 'dexcom-f4d1b',
    authDomain: 'dexcom-f4d1b.firebaseapp.com',
    storageBucket: 'dexcom-f4d1b.firebasestorage.app',
    measurementId: 'G-G8KVL76623',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr56EYSD5L40KEtnRpMy-VFYjpdqGSk_s',
    appId: '1:701912503570:android:4e8df4ce8fd7ff21ba8fcb',
    messagingSenderId: '701912503570',
    projectId: 'dexcom-f4d1b',
    storageBucket: 'dexcom-f4d1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaHDuP_IqPOcaXyTGq2jxkQfqxDrwgHr0',
    appId: '1:701912503570:ios:7ed5513793112f37ba8fcb',
    messagingSenderId: '701912503570',
    projectId: 'dexcom-f4d1b',
    storageBucket: 'dexcom-f4d1b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationDexcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaHDuP_IqPOcaXyTGq2jxkQfqxDrwgHr0',
    appId: '1:701912503570:ios:7ed5513793112f37ba8fcb',
    messagingSenderId: '701912503570',
    projectId: 'dexcom-f4d1b',
    storageBucket: 'dexcom-f4d1b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationDexcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeZKHgTw0oH_rJKPoA0pR3OvYV7f0b-lI',
    appId: '1:701912503570:web:620fa2cae0d017e1ba8fcb',
    messagingSenderId: '701912503570',
    projectId: 'dexcom-f4d1b',
    authDomain: 'dexcom-f4d1b.firebaseapp.com',
    storageBucket: 'dexcom-f4d1b.firebasestorage.app',
    measurementId: 'G-53L5DNSK61',
  );
}
